// Generated by IcedCoffeeScript 1.4.0c
var borrarPoligono, cambiaListaPoligonos, cargarPoligono, ft, inicializar, listaPoligonos, poligonoActual, propiedadesPoligono, quitarSeleccion, r;

r = null;

poligonoActual = void 0;

listaPoligonos = [];

ft = null;

inicializar = function() {
  r = Raphael("holder");
  r.rect(0, 0, 800, 600, 5).attr({
    stroke: "#666"
  });
  $("#agregar").click(cargarPoligono);
  $("#borrar").click(borrarPoligono);
  $("#liberar").click(quitarSeleccion);
  $("#listaPoligonos").change(cambiaListaPoligonos);
  return $("#reiniciar").click(function() {
    return poligonoActual.reset();
  });
};

cargarPoligono = function() {
  var l, nombre;
  if (poligonoActual !== void 0) poligonoActual.noEdit();
  poligonoActual = new Polygon(r);
  poligonoActual.add([[300, 100], [500, 100], [500, 150], [300, 150]], [300, 125, 330, 125, 470, 125, 500, 125]);
  poligonoActual.propiedades = {
    formaPoligono: "rectangulo",
    formaBezier: "recta",
    numeroFilas: 2,
    cuadrosPorFilas: [10, 12]
  };
  nombre = prompt("Nombre de la Poligono");
  l = listaPoligonos.length;
  $("#listaPoligonos").append("<option id='Poligono_" + l + "' value='" + l + "'>" + nombre + "</option>");
  listaPoligonos.push(poligonoActual);
  $("#Poligono_" + l).attr("selected", "selected");
  propiedadesPoligono();
};

propiedadesPoligono = function() {
  var cuadroFila, propiedades, _i, _len, _ref;
  $("#propiedadesPoligono").show();
  propiedades = poligonoActual.propiedades;
  $("#formaPoligono").val(propiedades.formaPoligono);
  $("#formaBezier").val(propiedades.formaBezier);
  $("#numeroFilas").val(propiedades.numeroFilas);
  $("#cuadrosPorFilas").empty();
  _ref = propiedades.cuadrosPorFilas;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    cuadroFila = _ref[_i];
    $("#cuadrosPorFilas").append("Fila " + (_i + 1) + ": <input id='cuadrosPorFilas_" + _i + "' value='" + cuadroFila + "' /><br>");
  }
};

cambiaListaPoligonos = function() {
  if (poligonoActual !== void 0) poligonoActual.noEdit();
  $("#listaPoligonos option:selected").each(function() {
    if ($(this).val() !== "-1") {
      poligonoActual = listaPoligonos[$(this).val()];
      poligonoActual.edit();
      return $("#propiedadesPoligono").show();
    } else {
      return $("#propiedadesPoligono").hide();
    }
  });
};

borrarPoligono = function() {
  var p, _i, _len;
  if (poligonoActual !== void 0) {
    for (_i = 0, _len = listaPoligonos.length; _i < _len; _i++) {
      p = listaPoligonos[_i];
      if (poligonoActual === p) {
        listaPoligonos[_i] = void 0;
        poligonoActual.del();
        poligonoActual = void 0;
        $("#listaPoligonos option:selected").remove();
        $("#propiedadesPoligono").hide();
        break;
      }
    }
  }
};

quitarSeleccion = function() {
  if (poligonoActual !== void 0) poligonoActual.noEdit();
  poligonoActual = void 0;
  $('option:selected').removeAttr('selected');
  $("#none").attr("selected", true);
  $("#propiedadesPoligono").hide();
};
